### PR TITLE
Add multiprocessor compilation flag

### PR DESCRIPTION
**Pull request by riverar**
Serial compilation of translation units is a drag.

### CODE REVIEW

**Comment by dunhor** [comment]
There's a shared `Common.Build.props` at the root of the repo - any reason these weren't added there?

**Comment by riverar** [comment]
No reason, will add there. Thanks!

**Comment by riverar** [comment]
Dang, this one escaped my TODO. Will wrap this up tonight.

**Comment by riverar** [comment]
@dunhor @Scottj1s Moved to the .props.

**Pull request merged**
