### PR TITLE
  Full PrivateProfile support

### PR DESCRIPTION
**Pull request by TimMangan**
The PrivateProfile functions of the Windows API are used by some applications to read and write to INI files in a structured way.

The FileRedirectionFixup previously had only partial support for the Get/Write PriviateProfile functions, which is causing apps using a combination of supported/unsupportedfunctions to crash.  Additionally, one of the implemented function crashes in the ASCII case due to a bug.

The TraceFixup previously had no support for any of the PrivateProfile API functions.

This PR addresses the above and should resolve Issue #123

### CODE REVIEW

**Comment by dhoehna** [comment]
Hey Tim,

Sorry for the long wait for the review to happen.  Can you please add tests for the functions you added and to test to make sure the bug is fixed?  I don't want the bug to crop up in future iterations of PSF.

**Comment by TimMangan** [comment]
Tests have been added under the FIleSystemTest project.

**Comment by TimMangan** [comment]
Thank you.  PR#132 now submitted.  Tag, you’re it!

Regards,

Tim

**Comment by TimMangan** [comment]
Test functions were added as part of the PR.

**Pull request merged**
